services:
  - type: web
    name: node-api
    env: node
    rootDir: api
    buildCommand: npm install
    startCommand: node index.js
    plan: free

  - type: web
    name: flask-service
    env: python
    rootDir: flask-service
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:main
    plan: free

  - type: web
    name: react-client
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    plan: free