import React from "react";
import { motion } from "framer-motion";
import CircleProgress from "./CircleProgress";
import { CheckCircle, AlertTriangle } from "lucide-react";

import jsPDF from "jspdf";

import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  CartesianGrid,
} from "recharts";

export default function DiabetesResult({ result, onBack }) {
  if (!result) return null;

  const percent = Math.round(result.confidence * 100);
  const isHigh = percent >= 70;
  const data = result.userMetrics.metrics;

  // Individual Graph Data
  const glucoseData = [{ name: "Glucose", value: data.Glucose }];
  const bmiData = [{ name: "BMI", value: data.BMI }];
  const insulinData = [{ name: "Insulin", value: data.Insulin }];

  // ⭐ PREMIUM PDF DOWNLOAD — CLEAN FORMATTED VERSION
  const downloadPremiumPDF = () => {
    const pdf = new jsPDF("p", "mm", "a4");
    const pageWidth = pdf.internal.pageSize.getWidth();

    // HEADER BAR
    pdf.setFillColor(50, 70, 170);
    pdf.rect(0, 0, pageWidth, 28, "F");

    // TITLE
    pdf.setTextColor("#ffffff");
    pdf.setFontSize(22);
    pdf.setFont("helvetica", "bold");
    pdf.text("DIABETES HEALTH REPORT", pageWidth / 2, 18, { align: "center" });

    // RESET COLOR
    pdf.setTextColor("#000000");
    pdf.setFont("helvetica", "normal");

    let y = 45;

    // DATE
    pdf.setFontSize(12);
    pdf.text(`Date: ${new Date().toLocaleDateString()}`, 10, y);

    // Prediction & Confidence
    y += 15;
    pdf.setFontSize(14);
    pdf.setFont("helvetica", "bold");
    pdf.text("Prediction:", 10, y);
    pdf.setFont("helvetica", "normal");
    pdf.text(`${result.prediction}`, 45, y);

    y += 10;
    pdf.setFont("helvetica", "bold");
    pdf.text("Probability:", 10, y);
    pdf.setFont("helvetica", "normal");
    pdf.text(`${percent}%`, 45, y);

    // Metrics Section
    y += 20;
    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text("Patient Health Metrics:", 10, y);

    const metrics = [
      `• Glucose: ${data.Glucose}`,
      `• BMI: ${data.BMI}`,
      `• Insulin: ${data.Insulin}`,
      `• Age: ${data.Age}`,
      `• Pregnancies: ${data.Pregnancies}`,
      `• Blood Pressure: ${data.BloodPressure}`,
    ];

    y += 10;
    pdf.setFontSize(13);
    pdf.setFont("helvetica", "normal");
    metrics.forEach((m) => {
      pdf.text(m, 15, y);
      y += 8;
    });

    // Recommendations
    y += 10;
    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text("Suggestions:", 10, y);

    y += 10;
    pdf.setFontSize(13);
    pdf.setFont("helvetica", "normal");

    result.suggestions.forEach((s) => {
      pdf.text(`• ${s}`, 15, y);
      y += 8;
    });

    // FOOTER
    pdf.setFontSize(10);
    pdf.setTextColor("#666666");
    pdf.text(
      "Generated by Health Risk Prediction System © 2025",
      pageWidth / 2,
      290,
      { align: "center" }
    );

    pdf.save("diabetes-health-report.pdf");
  };

  return (
    <motion.div
      id="result-section"
      initial={{ opacity: 0, scale: 0.9 }}
      animate={{ opacity: 1, scale: 1 }}
      className="bg-white shadow-2xl rounded-2xl p-8 mx-auto max-w-6xl mt-20"
    >
      {/* Prediction Icon */}
      <div className="text-center">
        {isHigh ? (
          <AlertTriangle size={70} className="text-red-500 mx-auto" />
        ) : (
          <CheckCircle size={70} className="text-green-500 mx-auto" />
        )}
      </div>

      <h2
        className={`text-4xl font-bold text-center mt-4 ${
          isHigh ? "text-red-600" : "text-green-600"
        }`}
      >
        {result.prediction}
      </h2>

      {/* Probability Circle */}
      <div className="flex justify-center mt-6">
        <CircleProgress percent={percent} />
      </div>

      <p className="text-center mt-4 text-gray-700 text-lg">
        {isHigh
          ? "High risk detected ⚠️. Medical attention recommended."
          : percent >= 40
          ? "Moderate risk. Maintain healthy habits 🟡"
          : "Low risk detected ✔️ Stay consistent!"}
      </p>

      {/* GRAPH CARDS */}
      <div className="mt-10 grid grid-cols-1 md:grid-cols-3 gap-6">
        <GraphCard title="Glucose Level" data={glucoseData} color="#38bdf8" />
        <GraphCard title="BMI" data={bmiData} color="#34d399" />
        <GraphCard title="Insulin Level" data={insulinData} color="#fbbf24" />
      </div>

      {/* Suggestions */}
      <div className="mt-10">
        <h3 className="text-3xl font-bold text-gray-900 mb-4">
          📝 Suggestions:
        </h3>

        <div className="space-y-4">
          {result.suggestions.map((s, i) => {
            let emoji = "💡";
            if (/doctor|medical|consult/i.test(s)) emoji = "🚨";
            else if (/avoid|reduce|control/i.test(s)) emoji = "⚠️";
            else if (/exercise|diet|walk/i.test(s)) emoji = "💪";

            return (
              <div
                key={i}
                className="p-4 bg-gray-50 border-l-8 rounded-lg shadow-sm flex gap-3 border-indigo-400"
              >
                <span className="text-3xl">{emoji}</span>
                <p className="text-gray-700 text-lg">{s}</p>
              </div>
            );
          })}
        </div>
      </div>

      {/* BUTTONS SIDE-BY-SIDE */}
      <div className="mt-12 flex justify-center gap-6">
        {/* Download Report Button */}
        <button
          onClick={downloadPremiumPDF}
          className="px-8 py-3 rounded-xl text-lg font-semibold text-white 
               bg-gradient-to-r from-red-500 to-red-600 
               shadow-lg hover:scale-105 transition-all duration-300"
        >
          📄 Download Report
        </button>

        {/* Back Button */}
        <button
          onClick={onBack}
          className="px-8 py-3 rounded-xl text-lg font-semibold text-white 
               bg-gradient-to-r from-indigo-500 to-indigo-600
               shadow-lg hover:scale-105 transition-all duration-300"
        >
          ← Back to Prediction
        </button>
      </div>
    </motion.div>
  );
}

/* REUSABLE GRAPH CARD COMPONENT */
function GraphCard({ title, data, color }) {
  return (
    <div className="bg-gray-50 p-6 rounded-xl shadow">
      <h3 className="text-xl font-semibold mb-3 text-center">{title}</h3>

      <ResponsiveContainer width="100%" height={220}>
        <BarChart data={data}>
          <CartesianGrid strokeDasharray="3 3" />
          <XAxis dataKey="name" />
          <YAxis domain={[0, data[0].value + 20]} />
          <Tooltip />
          <Bar dataKey="value" fill={color} radius={[10, 10, 0, 0]} />
        </BarChart>
      </ResponsiveContainer>
    </div>
  );
}
